/* 
//////////////////////////
Array de deck de jugador
/////////////////////////
 */

const deckArray = [
    {
        name: 'A of hearts',
        type: 'Hearts',
        icon: 'A',
        value: 1,
        img: '/img/baraja/hearts_Ace_Player.png',
    },
    {
        name: '2 of hearts',
        type: 'Hearts',
        icon: 2,
        value: 2,
        img: '/img/baraja/hearts_2_Player.png',
    },
    {
        name: '3 of hearts',
        type: 'Hearts',
        icon: 3,
        value: 3,
        img: '/img/baraja/hearts_3_Player.png',
    },
    {
        name: '4 of hearts',
        type: 'Hearts',
        icon: 4,
        value: 4,
        img: '/img/baraja/hearts_4_Player.png',
    },
    {
        name: '5 of hearts',
        type: 'Hearts',
        icon: 5,
        value: 5,
        img: '/img/baraja/hearts_5_Player.png',
    },
    {
        name: '6 of hearts',
        type: 'Hearts',
        icon: 6,
        value: 6,
        img: '/img/baraja/hearts_6_Player.png',
    },
    {
        name: '7 of hearts',
        type: 'Hearts',
        icon: 7,
        value: 7,
        img: '/img/baraja/hearts_7_Player.png',
    },
    {
        name: '8 of hearts',
        type: 'Hearts',
        icon: 8,
        value: 8,
        img: '/img/baraja/hearts_8_Player.png',
    },
    {
        name: '9 of hearts',
        type: 'Hearts',
        icon: 9,
        value: 9,
        img: '/img/baraja/hearts_9_Player.png',
    },
    {
        name: '10 of hearts',
        type: 'Hearts',
        icon: 10,
        value: 10,
        img: '/img/baraja/hearts_10_Player.png',
    },
    {
        name: 'J of hearts',
        type: 'Hearts',
        icon: 'J',
        value: 10,
        img: '/img/baraja/hearts_Jack_Player.png',
    },
    {
        name: 'Q of hearts',
        type: 'Hearts',
        icon: 'Q',
        value: 10,
        img: '/img/baraja/hearts_Queen_Player.png',
    },
    {
        name: 'K of hearts',
        type: 'Hearts',
        icon: 'K',
        value: 10,
        img: '/img/baraja/hearts_King_Player.png',
    },
    {
        name: 'A of spades',
        type: 'Spades',
        icon: 'A',
        value: 1,
        img: '/img/baraja/spades_Ace_Player.png',
    },
    {
        name: '2 of spades',
        type: 'Spades',
        icon: 2,
        value: 2,
        img: '/img/baraja/spades_2_Player.png',
    },
    {
        name: '3 of spades',
        type: 'Spades',
        icon: 3,
        value: 3,
        img: '/img/baraja/spades_3_Player.png',
    },
    {
        name: '4 of spades',
        type: 'Spades',
        icon: 4,
        value: 4,
        img: '/img/baraja/spades_4_Player.png',
    },
    {
        name: '5 of spades',
        type: 'Spades',
        icon: 5,
        value: 5,
        img: '/img/baraja/spades_5_Player.png',
    },
    {
        name: '6 of spades',
        type: 'Spades',
        icon: 6,
        value: 6,
        img: '/img/baraja/spades_6_Player.png',
    },
    {
        name: '7 of spades',
        type: 'Spades',
        icon: 7,
        value: 7,
        img: '/img/baraja/spades_7_Player.png',
    },
    {
        name: '8 of spades',
        type: 'Spades',
        icon: 8,
        value: 8,
        img: '/img/baraja/spades_8_Player.png',
    },
    {
        name: '9 of spades',
        type: 'Spades',
        icon: 9,
        value: 9,
        img: '/img/baraja/spades_9_Player.png',
    },

    {
        name: '10 of spades',
        type: 'Spades',
        icon: 10,
        value: 10,
        img: '/img/baraja/spades_10_Player.png',
    },
    {
        name: 'J of spades',
        type: 'Spades',
        icon: 'J',
        value: 10,
        img: '/img/baraja/spades_Jack_Player.png',
    },
    {
        name: 'Q of spades',
        type: 'Spades',
        icon: 'Q',
        value: 10,
        img: '/img/baraja/spades_Queen_Player.png',
    },
    {
        name: 'K of spades',
        type: 'Spades',
        icon: 'K',
        value: 10,
        img: '/img/baraja/spades_King_Player.png',
    },
    {
        name: 'A of diamonds',
        type: 'Diamonds',
        icon: 'A',
        value: 1,
        img: '/img/baraja/diamonds_Ace_Player.png',
    },
    {
        name: '2 of diamonds',
        type: 'Diamonds',
        icon: 2,
        value: 2,
        img: '/img/baraja/diamonds_2_Player.png',
    },
    {
        name: '3 of diamonds',
        type: 'Diamonds',
        icon: 3,
        value: 3,
        img: '/img/baraja/diamonds_3_Player.png',
    },
    {
        name: '4 of diamonds',
        type: 'Diamonds',
        icon: 4,
        value: 4,
        img: '/img/baraja/diamonds_4_Player.png',
    },
    {
        name: '5 of diamonds',
        type: 'Diamonds',
        icon: 5,
        value: 5,
        img: '/img/baraja/diamonds_5_Player.png',
    },
    {
        name: '6 of diamonds',
        type: 'Diamonds',
        icon: 6,
        value: 6,
        img: '/img/baraja/diamonds_6_Player.png',
    },
    {
        name: '7 of diamonds',
        type: 'Diamonds',
        icon: 7,
        value: 7,
        img: '/img/baraja/diamonds_7_Player.png',
    },
    {
        name: '8 of diamonds',
        type: 'Diamonds',
        icon: 8,
        value: 8,
        img: '/img/baraja/diamonds_8_Player.png',
    },
    {
        name: '9 of diamonds',
        type: 'Diamonds',
        icon: 9,
        value: 9,
        img: '/img/baraja/diamonds_9_Player.png',
    },
    {
        name: '10 of diamonds',
        type: 'Diamonds',
        icon: 10,
        value: 10,
        img: '/img/baraja/diamonds_10_Player.png',
    },
    {
        name: 'J of diamonds',
        type: 'Diamonds',
        icon: 'J',
        value: 10,
        img: '/img/baraja/diamonds_Jack_Player.png',
    },
    {
        name: 'Q of diamonds',
        type: 'Diamonds',
        icon: 'Q',
        value: 10,
        img: '/img/baraja/diamonds_Queen_Player.png',
    },
    {
        name: 'K of diamonds',
        type: 'Diamonds',
        icon: 'K',
        value: 10,
        img: '/img/baraja/diamonds_King_Player.png',
    },
    {
        name: 'A of clubs',
        type: 'Clubs',
        icon: 'A',
        value: 1,
        img: '/img/baraja/clubs_Ace_Player.png',
    },
    { name: '2 of clubs', type: 'Clubs', icon: 2, value: 2, img: '/img/baraja/clubs_2_Player.png' },
    { name: '3 of clubs', type: 'Clubs', icon: 3, value: 3, img: '/img/baraja/clubs_3_Player.png' },
    { name: '4 of clubs', type: 'Clubs', icon: 4, value: 4, img: '/img/baraja/clubs_4_Player.png' },
    { name: '5 of clubs', type: 'Clubs', icon: 5, value: 5, img: '/img/baraja/clubs_5_Player.png' },
    { name: '6 of clubs', type: 'Clubs', icon: 6, value: 6, img: '/img/baraja/clubs_6_Player.png' },
    { name: '7 of clubs', type: 'Clubs', icon: 7, value: 7, img: '/img/baraja/clubs_7_Player.png' },
    { name: '8 of clubs', type: 'Clubs', icon: 8, value: 8, img: '/img/baraja/clubs_8_Player.png' },
    { name: '9 of clubs', type: 'Clubs', icon: 9, value: 9, img: '/img/baraja/clubs_9_Player.png' },
    {
        name: '10 of clubs',
        type: 'Clubs',
        icon: 10,
        value: 10,
        img: '/img/baraja/clubs_10_Player.png',
    },
    {
        name: 'J of clubs',
        type: 'Clubs',
        icon: 'J',
        value: 10,
        img: '/img/baraja/clubs_Jack_Player.png',
    },
    {
        name: 'Q of clubs',
        type: 'Clubs',
        icon: 'Q',
        value: 10,
        img: '/img/baraja/clubs_Queen_Player.png',
    },
    {
        name: 'K of clubs',
        type: 'Clubs',
        icon: 'K',
        value: 10,
        img: '/img/baraja/clubs_King_Player.png',
    },
];
